Resolve the path of a template before rendering it.
This improves the situation described in #21413 slightly and makes the
backtrace a bit more clear. Instead of:

```
File "/usr/lib/python2.7/site-packages/salt/utils/jinja.py", line
143, in get_source
    raise TemplateNotFound(template)
    TemplateNotFound: fail2ban/map.jinja
```
…the backtrace shows now:

```
  File "/usr/lib/python2.7/site-packages/salt/utils/jinja.py", line 125,
  in get_source
      filepath = readlink(path.join(spath, template))
OSError: [Errno 2] No such file or directory: '/var/cache/salt/minion/files/base/fail2ban/map.jinja'
```

Although it doesn't really solve the actual problem described in #21413,
it adds important safeguards.